"$schema" = 'https://starship.rs/config-schema.json'

format = """
$character\
[](fg:blue0)\
$os\
$username\
[](bg:fg1 fg:blue0)\
$directory\
[](fg:fg1 bg:fg2)\
$git_branch\
$git_status\
[](fg:fg2 bg:fg3)\
$c\
$golang\
$nodejs\
$python\
$rust\
[](fg:fg3 bg:fg4)\
$docker_context\
[](fg:fg4)\
[\n](bold)
"""

palette = "gruvbox_dark"

[character]
success_symbol = '[󰧞](bold aqua)'
error_symbol = '[󰧞](bold red)'

[username]
show_always = false
style_user = "bg:blue0 fg:bg0"
style_root = "bg:blue0 fg:bg0"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:blue0 fg:bg0"
disabled = false # Disabled by default

[os.symbols]
Debian = " "

[directory]
style = "bg:fg1 fg:bg0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:fg3 fg:bg0"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:fg4 fg:bg0"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "bg:fg2 fg:bg0"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:fg2 fg:bg0"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:fg3 fg:bg0"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:fg3 fg:bg0"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:fg3 fg:bg0"
format = '[ $symbol ($version) ]($style)'

[palettes.gruvbox_dark]
bg = "#282828"
bg0 = "#282828"
bg0_h = "#1d2021"
bg0_s = "#32302f"
bg1 = "#3c3836"
bg2 = "#504945"
bg3 = "#665c54"
bg4 = "#7c6f64"
fg = "#ebdbb2"
fg0 = "#fbf1c7"
fg1 = "#ebdbb2"
fg2 = "#d5c4a1"
fg3 = "#bdae93"
fg4 = "#a89984"
gray = "#a89984"
gray0 = "#928374"
red = "#cc241d"
red0 = "#fb4934"
green = "#98971a"
green0 = "#b8bb26"
yellow = "#d79921"
yellow0 = "#fabd2f"
blue = "#458588"
blue0 = "#83a598"
purple = "#b16286"
purple0 = "#d3869b"
aqua = "#689d6a"
aqua0 = "#8ec07c"
orange = "#d65d0e"
orange0 = "#fe8019"